# .github/FUNDING.yml
# GitHub Sponsors is the only funding platform in use.
# Tiers: $5/mo (sponsor badge) · $50/mo (enterprise license + direct support)
# $100/mo (enterprise license + Slack access). One-time and custom amounts accepted.
# https://github.com/sponsors/taylorwilsdon
github: taylorwilsdon
