{
  "discoveryVersion": "v1",
  "revision": "20260923",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "documentationLink": "https://cloud.google.com/identity/",
  "version": "v1beta1",
  "ownerName": "Google",
  "servicePath": "",
  "canonicalName": "Cloud Identity",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "description": "API for provisioning and managing identity resources.",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "name": "cloudidentity",
  "version_module": true,
  "batchPath": "batch",
  "resources": {
    "groups": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.create",
          "flatPath": "v1beta1/groups",
          "httpMethod": "POST",
          "path": "v1beta1/groups",
          "description": "Creates a `Group`."
        },
        "lookup": {
          "httpMethod": "GET",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.lookup",
          "flatPath": "v1beta1/groups:lookup",
          "path": "v1beta1/groups:lookup"
        },
        "list": {
          "description": "Lists the `Group` resources under a customer or namespace.",
          "httpMethod": "GET",
          "id": "cloudidentity.groups.list",
          "flatPath": "v1beta1/groups",
          "path": "v1beta1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "patch": {
          "description": "Updates a `Group`.",
          "id": "cloudidentity.groups.patch",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH"
        },
        "search": {
          "id": "cloudidentity.groups.search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/groups:search",
          "description": "Searches for `Group` resources matching a specified query.",
          "httpMethod": "GET",
          "flatPath": "v1beta1/groups:search"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.get",
          "path": "v1beta1/{+name}",
          "description": "Retrieves a `Group`.",
          "httpMethod": "GET",
          "flatPath": "v1beta1/groups/{groupsId}"
        },
        "delete": {
          "description": "Deletes a `Group`.",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.groups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE",
          "flatPath": "v1beta1/groups/{groupsId}"
        },
        "updateSecuritySettings": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/{+name}",
          "description": "Update Security Settings",
          "flatPath": "v1beta1/groups/{groupsId}/securitySettings",
          "id": "cloudidentity.groups.updateSecuritySettings",
          "httpMethod": "PATCH"
        },
        "getSecuritySettings": {
          "httpMethod": "GET",
          "flatPath": "v1beta1/groups/{groupsId}/securitySettings",
          "path": "v1beta1/{+name}",
          "description": "Get Security Settings",
          "id": "cloudidentity.groups.getSecuritySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "searchTransitiveMemberships": {
              "path": "v1beta1/{+parent}/memberships:searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships"
            },
            "searchTransitiveGroups": {
              "path": "v1beta1/{+parent}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveGroups"
            },
            "modifyMembershipRoles": {
              "httpMethod": "POST",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "path": "v1beta1/{+name}:modifyMembershipRoles",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "id": "cloudidentity.groups.memberships.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a `Membership`.",
              "path": "v1beta1/{+name}"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1beta1/{+name}",
              "description": "Retrieves a `Membership`.",
              "id": "cloudidentity.groups.memberships.get"
            },
            "searchDirectGroups": {
              "path": "v1beta1/{+parent}/memberships:searchDirectGroups",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchDirectGroups",
              "description": "Searches direct groups of a member. Groups for which the actor does not have the permission to view memberships are silently filtered out.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.searchDirectGroups"
            },
            "create": {
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "path": "v1beta1/{+parent}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.create",
              "description": "Creates a `Membership`.",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+parent}/memberships",
              "httpMethod": "GET",
              "description": "Lists the `Membership`s within a `Group`.",
              "id": "cloudidentity.groups.memberships.list"
            },
            "lookup": {
              "path": "v1beta1/{+parent}/memberships:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.lookup",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`."
            },
            "getMembershipGraph": {
              "httpMethod": "GET",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the response will contain all membership paths between the group and the member.",
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "path": "v1beta1/{+parent}/memberships:getMembershipGraph",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "checkTransitiveMembership": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1beta1/{+parent}/memberships:checkTransitiveMembership",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor must have view permissions to at least one transitive membership between the member and group.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:checkTransitiveMembership"
            }
          }
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "delete": {
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "httpMethod": "DELETE",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.delete"
        },
        "patch": {
          "path": "v1beta1/{+name}",
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1beta1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "flatPath": "v1beta1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "description": "Gets an InboundSsoAssignment.",
          "httpMethod": "GET",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta1/inboundSsoAssignments/{inboundSsoAssignmentsId}"
        },
        "create": {
          "httpMethod": "POST",
          "flatPath": "v1beta1/inboundSsoAssignments",
          "path": "v1beta1/inboundSsoAssignments",
          "id": "cloudidentity.inboundSsoAssignments.create",
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "flatPath": "v1beta1/inboundSsoAssignments",
          "id": "cloudidentity.inboundSsoAssignments.list",
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "httpMethod": "GET",
          "path": "v1beta1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Gets the client state for the device user",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "path": "v1beta1/{+name}"
                },
                "patch": {
                  "path": "v1beta1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                }
              }
            }
          },
          "methods": {
            "wipe": {
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "path": "v1beta1/{+name}:wipe",
              "description": "Wipes the user's account on a device.",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "httpMethod": "POST"
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1beta1/{+name}:approve",
              "description": "Approves device to access user data.",
              "httpMethod": "POST",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1beta1/{+name}",
              "httpMethod": "DELETE",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}"
            },
            "cancelWipe": {
              "httpMethod": "POST",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "path": "v1beta1/{+name}:cancelWipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ]
            },
            "lookup": {
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "path": "v1beta1/{+parent}:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers:lookup"
            },
            "get": {
              "description": "Retrieves the specified DeviceUser",
              "path": "v1beta1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "GET",
              "id": "cloudidentity.devices.deviceUsers.get"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers",
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list",
              "path": "v1beta1/{+parent}/deviceUsers",
              "httpMethod": "GET"
            },
            "block": {
              "description": "Blocks device from accessing user data",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.block",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "path": "v1beta1/{+name}:block"
            }
          }
        }
      },
      "methods": {
        "delete": {
          "id": "cloudidentity.devices.delete",
          "path": "v1beta1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Deletes the specified device.",
          "flatPath": "v1beta1/devices/{devicesId}",
          "httpMethod": "DELETE"
        },
        "wipe": {
          "flatPath": "v1beta1/devices/{devicesId}:wipe",
          "description": "Wipes all data on the specified device.",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.wipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "path": "v1beta1/{+name}:wipe"
        },
        "cancelWipe": {
          "flatPath": "v1beta1/devices/{devicesId}:cancelWipe",
          "path": "v1beta1/{+name}:cancelWipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.cancelWipe"
        },
        "get": {
          "id": "cloudidentity.devices.get",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "httpMethod": "GET",
          "description": "Retrieves the specified device."
        },
        "create": {
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "id": "cloudidentity.devices.create",
          "flatPath": "v1beta1/devices",
          "path": "v1beta1/devices"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "path": "v1beta1/devices",
          "flatPath": "v1beta1/devices",
          "id": "cloudidentity.devices.list",
          "httpMethod": "GET",
          "description": "Lists/Searches devices."
        }
      }
    },
    "inboundSamlSsoProfiles": {
      "resources": {
        "idpCredentials": {
          "methods": {
            "list": {
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile.",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+parent}/idpCredentials",
              "httpMethod": "GET"
            },
            "delete": {
              "path": "v1beta1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes an IdpCredential.",
              "httpMethod": "DELETE",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "description": "Gets an IdpCredential.",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "add": {
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "path": "v1beta1/{+parent}/idpCredentials:add",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "POST",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`."
            }
          }
        }
      },
      "methods": {
        "delete": {
          "description": "Deletes an InboundSamlSsoProfile.",
          "path": "v1beta1/{+name}",
          "httpMethod": "DELETE",
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1beta1/inboundSamlSsoProfiles",
          "description": "Lists InboundSamlSsoProfiles for a customer.",
          "flatPath": "v1beta1/inboundSamlSsoProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSamlSsoProfiles.list"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/{+name}",
          "description": "Updates an InboundSamlSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "description": "Gets an InboundSamlSsoProfile.",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET"
        },
        "create": {
          "path": "v1beta1/inboundSamlSsoProfiles",
          "id": "cloudidentity.inboundSamlSsoProfiles.create",
          "description": "Creates an InboundSamlSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta1/inboundSamlSsoProfiles",
          "httpMethod": "POST"
        }
      }
    },
    "inboundOidcSsoProfiles": {
      "methods": {
        "create": {
          "id": "cloudidentity.inboundOidcSsoProfiles.create",
          "path": "v1beta1/inboundOidcSsoProfiles",
          "description": "Creates an InboundOidcSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST",
          "flatPath": "v1beta1/inboundOidcSsoProfiles"
        },
        "list": {
          "flatPath": "v1beta1/inboundOidcSsoProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1beta1/inboundOidcSsoProfiles",
          "id": "cloudidentity.inboundOidcSsoProfiles.list",
          "description": "Lists InboundOidcSsoProfile objects for a Google enterprise customer."
        },
        "patch": {
          "description": "Updates an InboundOidcSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "httpMethod": "PATCH",
          "id": "cloudidentity.inboundOidcSsoProfiles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}"
        },
        "delete": {
          "path": "v1beta1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundOidcSsoProfiles.delete",
          "flatPath": "v1beta1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "description": "Deletes an InboundOidcSsoProfile.",
          "httpMethod": "DELETE"
        },
        "get": {
          "flatPath": "v1beta1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundOidcSsoProfiles.get",
          "path": "v1beta1/{+name}",
          "httpMethod": "GET",
          "description": "Gets an InboundOidcSsoProfile."
        }
      }
    },
    "allowlistedDomains": {
      "methods": {
        "create": {
          "description": "Adds a domain to the allowlist.",
          "path": "v1beta1/allowlistedDomains",
          "flatPath": "v1beta1/allowlistedDomains",
          "id": "cloudidentity.allowlistedDomains.create",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "path": "v1beta1/allowlistedDomains",
          "flatPath": "v1beta1/allowlistedDomains",
          "id": "cloudidentity.allowlistedDomains.list",
          "description": "Lists the domains in the allowlist.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains",
            "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains.readonly"
          ],
          "httpMethod": "GET"
        },
        "delete": {
          "path": "v1beta1/{+name}",
          "description": "Removes a domain from the allowlist.",
          "httpMethod": "DELETE",
          "flatPath": "v1beta1/allowlistedDomains/{allowlistedDomainsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains"
          ],
          "id": "cloudidentity.allowlistedDomains.delete"
        },
        "get": {
          "description": "Retrieves a specific domain from the allowlist.",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.allowlistedDomains.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains",
            "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1beta1/allowlistedDomains/{allowlistedDomainsId}"
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "cancel": {
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "httpMethod": "POST",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "description": "Cancels a UserInvitation that was already sent.",
              "path": "v1beta1/{+name}:cancel"
            },
            "get": {
              "id": "cloudidentity.customers.userinvitations.get",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "httpMethod": "GET",
              "path": "v1beta1/{+name}"
            },
            "list": {
              "flatPath": "v1beta1/customers/{customersId}/userinvitations",
              "id": "cloudidentity.customers.userinvitations.list",
              "path": "v1beta1/{+parent}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET"
            },
            "isInvitableUser": {
              "httpMethod": "GET",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "path": "v1beta1/{+name}:isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser"
            },
            "send": {
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "httpMethod": "POST",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "path": "v1beta1/{+name}:send",
              "id": "cloudidentity.customers.userinvitations.send"
            }
          }
        }
      }
    },
    "orgUnits": {
      "resources": {
        "memberships": {
          "methods": {
            "list": {
              "description": "List OrgMembership resources in an OrgUnit treated as 'parent'. Parent format: orgUnits/{$orgUnitId} where `$orgUnitId` is the `orgUnitId` from the [Admin SDK `OrgUnit` resource](https://developers.google.com/admin-sdk/directory/reference/rest/v1/orgunits)",
              "id": "cloudidentity.orgUnits.memberships.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.orgunits",
                "https://www.googleapis.com/auth/cloud-identity.orgunits.readonly"
              ],
              "flatPath": "v1beta1/orgUnits/{orgUnitsId}/memberships",
              "path": "v1beta1/{+parent}/memberships"
            },
            "move": {
              "path": "v1beta1/{+name}:move",
              "id": "cloudidentity.orgUnits.memberships.move",
              "httpMethod": "POST",
              "flatPath": "v1beta1/orgUnits/{orgUnitsId}/memberships/{membershipsId}:move",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.orgunits"
              ],
              "description": "Move an OrgMembership to a new OrgUnit. NOTE: This is an atomic copy-and-delete. The resource will have a new copy under the destination OrgUnit and be deleted from the source OrgUnit. The resource can only be searched under the destination OrgUnit afterwards."
            }
          }
        }
      }
    },
    "policies": {
      "methods": {
        "list": {
          "path": "v1beta1/policies",
          "description": "List policies.",
          "id": "cloudidentity.policies.list",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1beta1/policies"
        },
        "create": {
          "id": "cloudidentity.policies.create",
          "path": "v1beta1/policies",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies"
          ],
          "httpMethod": "POST",
          "description": "Create a policy.",
          "flatPath": "v1beta1/policies"
        },
        "patch": {
          "flatPath": "v1beta1/policies/{policiesId}",
          "path": "v1beta1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies"
          ],
          "id": "cloudidentity.policies.patch",
          "httpMethod": "PATCH",
          "description": "Update a policy."
        },
        "get": {
          "flatPath": "v1beta1/policies/{policiesId}",
          "httpMethod": "GET",
          "description": "Get a policy.",
          "path": "v1beta1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "id": "cloudidentity.policies.get"
        },
        "delete": {
          "flatPath": "v1beta1/policies/{policiesId}",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.policies.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies"
          ],
          "description": "Delete a policy."
        }
      }
    }
  },
  "title": "Cloud Identity API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly": {
          "description": "See all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso": {
          "description": "See and edit all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.policies.readonly": {
          "description": "See policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.orgunits": {
          "description": "List, Move orgmembers of an OrgUnit in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.orgunits.readonly": {
          "description": "List org members of an OrgUnit in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains.readonly": {
          "description": "See allowlisted domains in your Cloud Identity Organization"
        },
        "https://www.googleapis.com/auth/cloud-identity.allowlisteddomains": {
          "description": "See and edit allowlisted domains in your Cloud Identity Organization"
        },
        "https://www.googleapis.com/auth/cloud-identity.policies": {
          "description": "See and edit policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "protocol": "rest",
  "basePath": "",
  "ownerDomain": "google.com",
  "id": "cloudidentity:v1beta1"
}
